module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  safelist: [
    'fas',
    'fa-folder-open',
    'fa-eye',
    'fa-search',
    'fa-chevron-down',
    'fa-filter',
    'fa-th-large',
    'fa-video',
    'fa-headphones-alt',
    'fa-image',
    'fa-file-alt',
    'fa-leaf',
    'fa-hand-sparkles',
    'fa-music',
    'fa-book',
    'fa-language',
    'fa-folder',
    'fa-clock',
    'fa-user-edit',
    'fa-download',
    'bg-gradient-to-r',
    'from-orange-500',
    'to-amber-500',
    'text-white',
    'shadow-orange-200',
    'from-gray-50',
    'to-gray-100',
    'text-gray-700',
    'hover:from-gray-100',
    'hover:to-gray-200',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
